---
abstract: 'Polymorphic data cloning'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.88
  Test::Requires: 0.03
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.59
  ExtUtils::ParseXS: 3.18
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::Clone
name: Data-Clone
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  XSLoader: 0.02
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Data-Clone.git
version: 0.004
